channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==1.26.2
  - pandas==2.1.4
  - psutil==5.9.8
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - xgboost==2.1.3
name: mlflow-env
